
-- LPG E-commerce Database Schema for Supabase
-- Run this in Supabase SQL Editor

-- Enable Row Level Security
ALTER DATABASE postgres SET "app.jwt_secret" TO 'your-jwt-secret-here';

-- Create custom types
CREATE TYPE user_role AS ENUM ('admin', 'customer');
CREATE TYPE order_status AS ENUM ('pending', 'confirmed', 'preparing', 'out_for_delivery', 'delivered', 'cancelled');
CREATE TYPE payment_method AS ENUM ('cod', 'gcash');
CREATE TYPE product_option AS ENUM ('swap', 'new');
CREATE TYPE alert_type AS ENUM ('low_stock', 'out_of_stock');

-- Users table (extends Supabase auth.users)
CREATE TABLE users (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  email TEXT NOT NULL UNIQUE,
  full_name TEXT NOT NULL,
  phone TEXT,
  address TEXT,
  role user_role NOT NULL DEFAULT 'customer',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Admins table (for default admin login)
CREATE TABLE admins (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  username TEXT NOT NULL UNIQUE,
  password_hash TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Products table
CREATE TABLE products (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  name TEXT NOT NULL,
  description TEXT,
  weight TEXT NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  image_url TEXT,
  option product_option NOT NULL,
  stock_quantity INTEGER NOT NULL DEFAULT 0,
  is_active BOOLEAN NOT NULL DEFAULT true,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Orders table
CREATE TABLE orders (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  total_amount DECIMAL(10,2) NOT NULL,
  payment_method payment_method NOT NULL,
  status order_status NOT NULL DEFAULT 'pending',
  delivery_address TEXT NOT NULL,
  delivery_date TIMESTAMP WITH TIME ZONE,
  notes TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Order items table
CREATE TABLE order_items (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL,
  price DECIMAL(10,2) NOT NULL,
  option product_option NOT NULL
);

-- Chat messages table
CREATE TABLE chat_messages (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID REFERENCES orders(id) ON DELETE CASCADE,
  sender_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  message TEXT NOT NULL,
  is_read BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Receipts table
CREATE TABLE receipts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  receipt_url TEXT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Location tracking table
CREATE TABLE locations (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id UUID NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  latitude DECIMAL(10,8) NOT NULL,
  longitude DECIMAL(11,8) NOT NULL,
  timestamp TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Stock alerts table
CREATE TABLE stock_alerts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  product_id UUID NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  product_name TEXT NOT NULL,
  current_stock INTEGER NOT NULL,
  threshold INTEGER NOT NULL,
  alert_type alert_type NOT NULL,
  is_resolved BOOLEAN NOT NULL DEFAULT false,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  resolved_at TIMESTAMP WITH TIME ZONE
);

-- Create indexes for better performance
CREATE INDEX idx_users_email ON users(email);
CREATE INDEX idx_users_role ON users(role);
CREATE INDEX idx_products_name ON products(name);
CREATE INDEX idx_products_option ON products(option);
CREATE INDEX idx_products_active ON products(is_active);
CREATE INDEX idx_orders_user ON orders(user_id);
CREATE INDEX idx_orders_status ON orders(status);
CREATE INDEX idx_orders_created_at ON orders(created_at);
CREATE INDEX idx_order_items_order ON order_items(order_id);
CREATE INDEX idx_order_items_product ON order_items(product_id);
CREATE INDEX idx_chat_messages_order ON chat_messages(order_id);
CREATE INDEX idx_chat_messages_sender ON chat_messages(sender_id);
CREATE INDEX idx_chat_messages_receiver ON chat_messages(receiver_id);
CREATE INDEX idx_chat_messages_created_at ON chat_messages(created_at);
CREATE INDEX idx_receipts_order ON receipts(order_id);
CREATE INDEX idx_locations_order ON locations(order_id);
CREATE INDEX idx_locations_timestamp ON locations(timestamp);
CREATE INDEX idx_stock_alerts_product ON stock_alerts(product_id);
CREATE INDEX idx_stock_alerts_type ON stock_alerts(alert_type);
CREATE INDEX idx_stock_alerts_resolved ON stock_alerts(is_resolved);

-- Insert default admin user (password: admin123)
-- Note: In production, use proper password hashing
INSERT INTO admins (username, password_hash) VALUES ('admin', '$2b$10$8K3VzJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGvJcGv